/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cocina.user_folder.Dialogos;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author drdr_
 */
public class DialogoEntrega extends javax.swing.JFrame {

    /**
     * Creates new form DialogoEntrega
     */
    
    DefaultListModel Lista = new DefaultListModel(); 
    DefaultListModel ListaK = new DefaultListModel(); 
    DefaultListModel ListaI = new DefaultListModel(); 
    ArrayList<String> lista_nombre = new ArrayList<>();
    ArrayList<String> lista_kilos = new ArrayList<>();
    ArrayList<String> lista_ids = new ArrayList<>();
    private int modificador = 0;
    private int value;
        
    public DialogoEntrega() {
        initComponents();
        this.setLocationRelativeTo(null);       
        hide_elements();
    }

    public DialogoEntrega(int id) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.value = id;
        modificador = 1;        
        consultar();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("pro_bd?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        insumos_1Query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT i FROM Insumos_1 i");
        insumos_1List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : insumos_1Query.getResultList();
        jPanel1 = new javax.swing.JPanel();
        tf_titulo = new javax.swing.JLabel();
        cancel_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_name = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        add_btn = new javax.swing.JButton();
        spinner_kilos = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        txt_selins = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_id = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        txt_idins = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList_cant = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        remove_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        label_name = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        output_name = new javax.swing.JLabel();
        output_id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tf_titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_titulo.setText("Nueva Entrega");

        cancel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alimentacion/VEntana Agregar/botoncancelar.png"))); // NOI18N
        cancel_btn.setBorder(null);
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alimentacion/VEntana Agregar/botonagregar.png"))); // NOI18N
        save_btn.setBorder(null);
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        jLabel3.setText("Kilos");

        jList_name.setModel(Lista       );
        jScrollPane1.setViewportView(jList_name);

        jLabel1.setText("Detalles");

        add_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alimentacion/VEntana Agregar/botonagregar.png"))); // NOI18N
        add_btn.setBorder(null);
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        txt_selins.setText("Insumo Seleccionado");

        jList_id.setModel(ListaI);
        jScrollPane3.setViewportView(jList_id);

        jLabel5.setText("ID");

        txt_idins.setText("...");

        jList_cant.setModel(ListaK);
        jScrollPane4.setViewportView(jList_cant);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, insumos_1List, jTable2);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idInsumo}"));
        columnBinding.setColumnName("Id Insumo");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombre}"));
        columnBinding.setColumnName("Nombre");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${categoria}"));
        columnBinding.setColumnName("Categoria");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable2);

        remove_btn.setBackground(new java.awt.Color(255, 102, 102));
        remove_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        remove_btn.setForeground(new java.awt.Color(255, 255, 255));
        remove_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alimentacion/HelpKitchen_quitar.png"))); // NOI18N
        remove_btn.setBorder(null);
        remove_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_btnActionPerformed(evt);
            }
        });

        delete_btn.setBackground(new java.awt.Color(255, 102, 102));
        delete_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alimentacion/HelpKitchen_Eliminar.png"))); // NOI18N
        delete_btn.setBorder(null);
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        label_name.setText("Nombre de Entrega");

        label_id.setText("ID");

        output_name.setText("...");

        output_id.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spinner_kilos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_selins)
                                    .addComponent(txt_idins, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(remove_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add_btn)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(delete_btn)
                        .addGap(34, 34, 34)
                        .addComponent(cancel_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(save_btn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_id)
                            .addComponent(label_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(output_name, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(output_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_name)
                                    .addComponent(output_name))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_id)
                                    .addComponent(output_id))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_idins))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_selins)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(add_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remove_btn)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spinner_kilos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancel_btn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(delete_btn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(save_btn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        if(modificador==1){
            add_values_to_lists();            
            grabar(getMax());
            sumarinsumo();            
        }else{
                        
        }
        
    }//GEN-LAST:event_save_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        String a = txt_selins.getText();
        int value = (int) spinner_kilos.getValue();
        String id = txt_idins.getText();        
        Lista.addElement(a);
        ListaK.addElement(value);
        ListaI.addElement(id);
    }//GEN-LAST:event_add_btnActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int fila = jTable2.getSelectedRow();
        int id = (int) jTable2.getValueAt(fila, 0);
        String nombre = (String) jTable2.getValueAt(fila, 1);        
        txt_idins.setText(String.valueOf(id));
        txt_selins.setText(nombre);                               
    }//GEN-LAST:event_jTable2MouseClicked

    private void remove_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_btnActionPerformed
        removeListElements();  
    }//GEN-LAST:event_remove_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        full_delete(Integer.valueOf(output_id.getText()));
    }//GEN-LAST:event_delete_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogoEntrega().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton delete_btn;
    private javax.persistence.EntityManager entityManager;
    private java.util.List<cocina.user_folder.Insumos_1> insumos_1List;
    private javax.persistence.Query insumos_1Query;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList_cant;
    private javax.swing.JList<String> jList_id;
    private javax.swing.JList<String> jList_name;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel output_id;
    private javax.swing.JLabel output_name;
    private javax.swing.JButton remove_btn;
    private javax.swing.JButton save_btn;
    private javax.swing.JSpinner spinner_kilos;
    private javax.swing.JLabel tf_titulo;
    private javax.swing.JLabel txt_idins;
    private javax.swing.JLabel txt_selins;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
           
    private String getMax() {   
        
        String sql_e = "insert into entregas values()";        
        connect_and_catch(sql_e,"Agregada Entrega"); 
        
        try{            
            Class.forName("com.mysql.jdbc.Driver");
            String cadena = "jdbc:mysql://localhost/pro_bd?user=root&password=qonmqa3p";
            Connection con = (Connection) DriverManager.getConnection(cadena);            
            PreparedStatement stmt = null;            
            
            ResultSet table;           
            String sql = "select max(id_entrega) from entregas";
            stmt = con.prepareStatement(sql);
            table = stmt.executeQuery();  
            
            while(table.next()){
                String max = table.getString(1);
                return max;                
            }
                                    
        }catch(ClassNotFoundException e1){
            JOptionPane.showMessageDialog(null,e1);
        }catch(SQLException e2){
            JOptionPane.showMessageDialog(null,e2);
        }catch(Exception e3){
            JOptionPane.showMessageDialog(null,e3);
        } 
        return "1";
    }
    
    private void sumarinsumo(){               
        
        for(int x=0;x<lista_kilos.size();x++){
            
            String valor_actual = null;
            
            try{            
                String ids = (String) lista_ids.get(x); 
                String kilos = (String) lista_kilos.get(x);
                
                Class.forName("com.mysql.jdbc.Driver");
                String cadena = "jdbc:mysql://localhost/pro_bd?user=root&password=qonmqa3p";
                Connection con = (Connection) DriverManager.getConnection(cadena);            
                PreparedStatement stmt = null;            

                ResultSet table;           
                String sql = "select cantidad from insumos where id_insumo = "
                        + ids;                    
                stmt = con.prepareStatement(sql);            
                table = stmt.executeQuery();  

                while(table.next()){
                    valor_actual = table.getString(1);
                }
                
                int valor_nuevo = Integer.valueOf(kilos) + Integer.valueOf(valor_actual);
                
                String update = "update insumos set cantidad = " + valor_nuevo + " where id_insumo = "
                        + ids;
                connect_and_catch(update, "Update al insumo");
                                    
            }catch(ClassNotFoundException e1){
                JOptionPane.showMessageDialog(null,e1);
            }catch(SQLException e2){
                JOptionPane.showMessageDialog(null,e2);
            }catch(Exception e3){
                JOptionPane.showMessageDialog(null,e3);
            }         
        }                  
    }
    
    private void grabar(String max) {        
                        
        for(int x=0;x<lista_ids.size();x++){         
            String ids = (String) lista_ids.get(x);            
            
            System.out.println(ids);
                
            String sql = "insert into entrega_elements(id_entrega,id_insumo) values("
                + max + ","                 
                + ids + ");";
        
            System.out.println(sql);
        
            connect_and_catch(sql,"Entrega Registrada"); 
        }       
        
    }
    
    private void connect_and_catch(String sql,String mensaje) {        
        try{            
            Class.forName("com.mysql.jdbc.Driver");
            String cadena = "jdbc:mysql://localhost/pro_bd?user=root&password=qonmqa3p";
            Connection con = (Connection) DriverManager.getConnection(cadena);            
            PreparedStatement stmt = null;            
            stmt=con.prepareStatement(sql);
            int sw=stmt.executeUpdate();            
            if(sw!=0){
                JOptionPane.showMessageDialog(null,mensaje);
                this.dispose();
            }                        
        }catch(ClassNotFoundException e1){
            JOptionPane.showMessageDialog(null,e1);
        }catch(SQLException e2){
            JOptionPane.showMessageDialog(null,e2);
        }catch(Exception e3){
            JOptionPane.showMessageDialog(null,e3);
        }    
    }

    private void consultar() {
        try{            
            Class.forName("com.mysql.jdbc.Driver");
            String cadena = "jdbc:mysql://localhost/pro_bd?user=root&password=qonmqa3p";
            Connection con = (Connection) DriverManager.getConnection(cadena);            
            PreparedStatement stmt = null;            
            
            ResultSet table;           
            String sql = "select * from entregas where "
                    + "id_entrega = " + value;                    
            stmt = con.prepareStatement(sql);            
            table = stmt.executeQuery();        
            while (table.next()){                
                output_id.setText(table.getString(1)); 
                output_name.setText(table.getString(2)); 
            }                        
            consultar_insumos(value);
                                    
        }catch(ClassNotFoundException e1){
            JOptionPane.showMessageDialog(null,e1);
        }catch(SQLException e2){
            JOptionPane.showMessageDialog(null,e2);
        }catch(Exception e3){
            JOptionPane.showMessageDialog(null,e3);
        }
    }
    
    private void consultar_insumos(int id) {
        try{    
            
            
            Class.forName("com.mysql.jdbc.Driver");
            String cadena = "jdbc:mysql://localhost/pro_bd?user=root&password=qonmqa3p";
            Connection con = (Connection) DriverManager.getConnection(cadena);            
            PreparedStatement stmt = null;            
            
            ResultSet table;           
            String sql = "select id_insumo from entrega_elements where "
                    + "id_entrega = " + id;                    
            stmt = con.prepareStatement(sql);            
            table = stmt.executeQuery();        
            while (table.next()){                                
                lista_ids.add(table.getString(1));
                ListaI.addElement(table.getString(1));
            }       
            
            PreparedStatement stmt2 = null;            
            
            ResultSet table2;           
            String a = "";
            
            for(int x=0;x<lista_ids.size();x++){                
                if(x==lista_ids.size()-1){
                    a = a + lista_ids.get(x);
                }else{
                    a = a + lista_ids.get(x) + "||";
                }
            }
            
            System.out.println(a);
            
            String sql2 = "select nombre,cantidad from insumos where "
                    + "id_insumo = " + a;   
            
            System.out.println(sql2);
            stmt2 = con.prepareStatement(sql2);            
            table2 = stmt2.executeQuery();        
            while (table2.next()){                            
                Lista.addElement(table2.getString(1));                
                ListaK.addElement(table2.getString(2));                      
            }         
            
            
                                    
        }catch(ClassNotFoundException e1){
            JOptionPane.showMessageDialog(null,e1);
        }catch(SQLException e2){
            JOptionPane.showMessageDialog(null,e2);
        }catch(Exception e3){
            JOptionPane.showMessageDialog(null,e3);
        }
    }

    private void full_delete(int id) {
        delete_elemements(value);
        delete_paquete(value);
        
    }
    
    private void delete_elemements(int id){
        String sql = "delete from paquetes_elements where id_paquete = " + id;
        connect_and_catch(sql,"Borrado");
    }
    
    private void delete_paquete(int id){
        String sql_2 = "delete from paquetes where id_paquete = " + id;             
        connect_and_catch(sql_2,"Borrado"); 
    }

    private void hide_elements() {
        output_id.setVisible(false);
        output_name.setVisible(false);
        label_name.setVisible(false);
        label_id.setVisible(false);  
        delete_btn.setVisible(false);
    }

    private void add_values_to_lists() {
        ListModel model_id = jList_id.getModel(); 
        ListModel model_name = jList_name.getModel(); 
        ListModel model_cant = jList_cant.getModel(); 
        
        for(int i=0; i < model_id.getSize(); i++){
            String id = (String) model_id.getElementAt(i);  
            String name = (String) model_name.getElementAt(i);
            String cant = (String) model_cant.getElementAt(i);
            lista_ids.add(id);
            lista_nombre.add(name);
            lista_kilos.add(cant);
        }       
        
    }

    private void removeListElements() {
        Lista.removeAllElements();
        ListaK.removeAllElements();
        ListaI.removeAllElements(); 
    }

}


