/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cocina.user_folder;

/**
 *
 * @author drdr_
 */
public class Paquetes_user extends javax.swing.JFrame {

    /**
     * Creates new form Paquetes_user
     */
    public Paquetes_user() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("bd?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        paquetesQuery = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT p FROM Paquetes p");
        paquetesList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : paquetesQuery.getResultList();
        paquetesQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT p FROM Paquetes p");
        paquetesList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : paquetesQuery1.getResultList();
        paquetesQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT p FROM Paquetes p");
        paquetesList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : paquetesQuery2.getResultList();
        paquetesQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT p FROM Paquetes p");
        paquetesList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : paquetesQuery3.getResultList();
        paquetesQuery4 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT p FROM Paquetes p");
        paquetesList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : paquetesQuery4.getResultList();
        paquetesQuery5 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT p FROM Paquetes p");
        paquetesList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : paquetesQuery5.getResultList();
        paquetesQuery6 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT p FROM Paquetes p");
        paquetesList6 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : paquetesQuery6.getResultList();
        paquetesQuery7 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT p FROM Paquetes p");
        paquetesList7 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : paquetesQuery7.getResultList();
        paquetesQuery8 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT p FROM Paquetes p");
        paquetesList8 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : paquetesQuery8.getResultList();
        paquetesQuery9 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT p FROM Paquetes p");
        paquetesList9 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : paquetesQuery9.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        slideMenu1 = new cocina.user_folder.SlideMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alimentacion/TABLA/Botonagregar.png"))); // NOI18N
        jButton1.setBorder(null);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, paquetesList9, jTable2);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idPaquete}"));
        columnBinding.setColumnName("Id Paquete");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idPaqueteElement}"));
        columnBinding.setColumnName("Id Paquete Element");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombre}"));
        columnBinding.setColumnName("Nombre");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);

        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(slideMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(slideMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paquetes_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paquetes_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paquetes_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paquetes_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paquetes_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager0;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private java.util.List<cocina.user_folder.Paquetes> paquetesList;
    private java.util.List<cocina.user_folder.Paquetes> paquetesList1;
    private java.util.List<cocina.user_folder.Paquetes> paquetesList2;
    private java.util.List<cocina.user_folder.Paquetes> paquetesList3;
    private java.util.List<cocina.user_folder.Paquetes> paquetesList4;
    private java.util.List<cocina.user_folder.Paquetes> paquetesList5;
    private java.util.List<cocina.user_folder.Paquetes> paquetesList6;
    private java.util.List<cocina.user_folder.Paquetes> paquetesList7;
    private java.util.List<cocina.user_folder.Paquetes> paquetesList8;
    private java.util.List<cocina.user_folder.Paquetes> paquetesList9;
    private javax.persistence.Query paquetesQuery;
    private javax.persistence.Query paquetesQuery1;
    private javax.persistence.Query paquetesQuery2;
    private javax.persistence.Query paquetesQuery3;
    private javax.persistence.Query paquetesQuery4;
    private javax.persistence.Query paquetesQuery5;
    private javax.persistence.Query paquetesQuery6;
    private javax.persistence.Query paquetesQuery7;
    private javax.persistence.Query paquetesQuery8;
    private javax.persistence.Query paquetesQuery9;
    private cocina.user_folder.SlideMenu slideMenu1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
